apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wmc3x192q-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wmc3x192q-java-quarkus-gitops